### ISSUE TITLE
Shared with me doesn't load shared files.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflow_twin_main#769]
1) As user "stevejobs" I shared a file called drukwerk-prijsvergelijking.docx in my quantum with user "fhfh"
2) As user "fhfh" I go to my shared files.

=> 

File is not there, it shows my root folder with two options removed.

![chrome_nievuOi1q7](https://user-images.githubusercontent.com/59569757/193864454-3d293fb2-d46a-4688-a349-222871f16b8d.gif)

If I check the network call it DOES list the correct file, but it's not showing it in the UI.

[{"id":"274db46b-157c-42fb-96bc-e12639d2ecff","path":"/appdata/storage/Drukwerk-prijsvergelijking.docx","owner":{"id":"stevejobs","location":"204:a802:b229:cca7:5447:79e7:e284:916e"},"name":"Drukwerk-prijsvergelijking.docx","isFolder":false,"isSharedWithMe":true,"size":15218,"lastModified":1664897907238,"permissions":[{"userId":"f2eef7c7-a7e8-4c5e-8dac-1a92ccafa3e0","sharePermissionTypes":["r"]},{"userId":"fhfh","sharePermissionTypes":["r"]}]}]

**Comment by JorisBassle** [comment]
This is because of a fix for  #399 
Now it is fixed in a better way. Big code cleanup there and now Monaco editor is in FileBrowser.vue instead of component FileTable.vue where it shouldn't be.
Components that need monaco editor now use it via emits.

Everything in Quantum should be tested again to be sure
