### ISSUE TITLE
Staging 1.7 - First login failed.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflow_twin_main#854]
Stuck on blank page 

![image](https://user-images.githubusercontent.com/59569757/202459937-3def3cfc-7582-4325-854e-66b4afe5b710.png)

Refresh + new try did work.

**Comment by JorisBassle** [comment]
Tried twice in incognito and worked. Removed running container before login to simulate first login.

**Comment by JorisBassle** [comment]
Problem:
A new version has been deployed on staging which removes all user containers. So going to your personal link (ex: jorisb.digitaltwin-test.jimbertesting.be) gives a 502 error since the container hasn't been spawned.

Expected Flow if container is not running:
- Going to your personal link gives a 502
- You get redirected from 'jorisb.digitaltwin-test.jimbertesting.be' to 'digitaltwin-test.jimbertesting.be?name=jorisb' (spawner)
- The spawner spawns the container and redirects you to the login screen

### Actual Flow:
- Going to your personal link tries to redirect you to 'digitaltwin-test.jimbertesting.be?name=jorisb'. But it gets stuck at a white screen because of CORS problems
Error:
Access to script at 'https://digitaltwin-test.jimbertesting.be/?username=jorisb' (redirected from 'https://jorisb.digitaltwin-test.jimbertesting.be/assets/index.ee83756a.js') from origin 'https://jorisb.digitaltwin-test.jimbertesting.be' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
![image](https://user-images.githubusercontent.com/36887810/206766058-566d1419-6bb9-464c-ad74-08aeffe6e051.png)


### Usefull files:
- https://github.com/threefoldtech/freeflow_twin_main/blob/development/apps/spawner/proxy/nginx.conf
- https://github.com/threefoldtech/freeflow_twin_main/blob/development/apps/spawner/frontend/src/views/Home.vue
- https://github.com/threefoldtech/freeflow_twin_main/blob/development/apps/spawner/frontend/src/service/spawnService.ts
- https://github.com/threefoldtech/freeflow_twin_main/blob/development/apps/spawner/server/src/routers/spawn.ts

**Comment by JorisBassle** [comment]
It has to do with the workbox-precache-v2. It caches files that no longer exist since the container is no longer running. Removing this fixes the white screen and redirects the user correctly to the spawner (digitaltwin-test.jimbertesting.be).
I am looking for a way to clear or update the workbox cache if a new version is uploaded.
See file:
https://github.com/threefoldtech/freeflow_twin_main/blob/06b66c5e02874a230aa77f5b03ad4a5beba599d1/apps/frontend/vite.config.ts#L30
